### ISSUE TITLE
wrong vendor price for an 5-charges item

### ISSUE THREAD

**Issue by MrMarvin** [shirsig/aux_merchant_prices#1]
http://www.wowhead.com/item=20744/minor-wizard-oil s currently sold (on Elysium PVP Realm) for 1s to a Vendor.
I see that wow-head and other sites list it at 5s. Maybe its just my Realm. Can anyone confirm? What is the price source for this addon anyway?

Oh and thanks a lot for making this one and the other addons! Great work! <3

**Comment by shirsig** [comment]
The source is an informant database for TBC (the vanilla ones were lacking items from aq and later).
Actually it seems to me that wizard oil sells for 1s per charge, so with 5 charges it sells for 5s.
However, aux actually expects the single charge price there so the vendor profit and such would be wrong. I'll fix that.

**Comment by shirsig** [comment]
fixed now. note that you have to do */run aux_merchant_prices_imported = false* and then */run ReloadUI()* for it to reimport the prices after an update.
