### ISSUE TITLE
Discussion about price source for which realm / patch set

### ISSUE THREAD

**Issue by MrMarvin** [shirsig/aux_merchant_prices#2]
After finding multiple items with "wrong" prices on my realm (Elysium PVP) and asking about the source for these prices in #1, I'd like to discuss if and how we should make this addon Vanilla / TBC or patch-level dependent.

For example http://db.vanillagaming.org/?item=2169 sells for 9s43c on my realm, which also is in my ancient Informant version: `Informant/InfData.lua:3188:	[2169]="4717:943:2:15:1:::0:0:", -- Buzzer Blade`, however this addons price source has it for 18s something.

I do see two possible ways to improve the price data for Vanilla realms:
1. first try to lookup an item price in Informant, if this fails, fall back to aux_merchant_prices TBC database.
2. Merge data from Informants latest vanilla release into aux_merchant_prices for existing items. Keep existing prices for items not in Informant.

I'd prefer 1 here.

However, to be honest the only improvement here would be for the experience when using the vendor profit functionality, which is only a small part of the awesome aux addon and I'm not sure if its worth the time.

**Comment by shirsig** [comment]
I'm gonna do 2 at some point. Should be fairly easy to automate.

**Comment by shirsig** [comment]
merged the databases now. hope most of it is correct now. In any case, the remaining ones will have to be fixed manually if someone reports them.
