### ISSUE TITLE
I have enabled the addon but vendor sell value is still "?"

### ISSUE THREAD

**Issue by Larsy93** [shirsig/aux_merchant_prices#4]
I have enabled the addon but vendor sell value is still "?"

**Comment by Larsy93** [comment]
https://i.gyazo.com/b77d28a6690628ba237040237dc8240d.png

https://i.gyazo.com/50c605ff17aeaa0783ec0497f15956a2.png

**Comment by shirsig** [comment]
do you have the newest aux version? try /run aux_merchant_prices_imported = nil and relog.

**Comment by Larsy93** [comment]
i have the newest version of Aux, i tried that, when i ran that command it set the vendor thingy to off, i relogged and tried re-enabling it but still says "?"

**Comment by shirsig** [comment]
sorry I copy pasted the wrong variable name, it's corrected now

**Comment by Larsy93** [comment]
That actually fixed it, thanks alot! 👍 Quick support :)

**Comment by shirsig** [comment]
You're welcome :) have a nice evening.
