### ISSUE TITLE
Wrong vendor prices

### ISSUE THREAD

**Issue by Twilldorm** [shirsig/aux_merchant_prices#7]
Hello, some items have wrong prices, e.g. Saltstone Legplates (https://db.vanillagaming.org/?item=14900) Addon shows higher value.

**Comment by shirsig** [comment]
You're confusing the vendor price and historical auction value?

**Comment by Twilldorm** [comment]
No, the vendor price (from the addon) for many green items actually higher, than their true selling price. For example, for some items AUX showed the vendor price about 1g, but when I bought them and tried to sell, actual selling price to vendor was about 60-70s. If you want I can make a screnshot for you later.

**Comment by shirsig** [comment]
https://github.com/shirsig/aux_merchant_prices/blob/master/aux_merchant_prices.lua
[14900] = 4298,

seems correct for Saltstone Legplates

**Comment by shirsig** [comment]
It may well be for items from after AQ because those were taken from a TBC database because informant doesn't have them, but all the other prices are actually taken from informant.

**Comment by Twilldorm** [comment]
I think there is a bug in copying prices from Informant. 
e.g. Farmer Dalson's Shotgun
`[13474] = "123624#0",` - aux_vendor_prices
`[13474]="123624:24724:2:3:1:::0:0:` - informant
Actual price - 2g47s24c 

As I understand, in the informant the second number is a vendor price, but the first number was copied to aux_vendor_prices

**Comment by Twilldorm** [comment]
Ok, I'll check inside the game, and will give you an example.

**Comment by Twilldorm** [comment]
![image](https://user-images.githubusercontent.com/34094761/33424499-16e24152-d5cd-11e7-9504-31b18661464a.png)

**Comment by Twilldorm** [comment]
Wow, I've just found, that in my aux_vendor_prices is different from the one on the github, Sorry for this ticket, I think now we may close it)
